---
title: "How to produce MAgPIE 4.0 emulators and use them in REMIND 2.0"
author: "David Klein"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# 1. MAgPIE runs
## 1.1 Start emulator runs
* checkout MAgPIE release branch
  * git clone git@gitlab.pik-potsdam.de:landuse/magpie.git
  * git checkout release
* in config/default.cfg specify the input data MAgPIE requires (make sure it has the correct region code)
* in config/scenario_config_emulator.csv specify emulator scenarios
* start emulator runs using Rscript start.R

## 1.2 Produce emulators
* after all MAgPIE runs are fished the emulators should be already availalbe
* if not, start the emulator scrip using Rscript output.R and debug the underlying script in scripts/output/single/emulator.R
  * -> 1 single
  * -> any number of ONE of the runs that belong to the scenario you want to produce the emulators for
  * -> 8: emulator
* this creates an "emulator" folder in the "output" folder, containing further subfolder for each scenario
* within the scenario folders the fit coefficients for the bioenergy supplycurves are stored in files like "f30_bioen_price_SSP2-26_690d3718e151be1b450b394c1064b1c5.cs4r"

## 1.3 Correct emulators if necessary (replace flat fits)
* place this code in a script in MAgPIE's output folder
* adapt it to your needs and run it to identify and replace flat fits
```
################################################################
################## 1.3 Replace flat fits #######################
################################################################

library(magclass)
library(remulator)
setwd("~/Documents/0_GIT/magpie4-model/output/")
load("emulator/SSP2-Ref/linear/data_postfit_SSP2-Ref.Rdata")

zero <- fitcoef[,,"b"]<0.01

#* replace fitcoefficients for years that have flat fits (b==0)
fc <- fill_missing_years(fitcoef,zero)

supplycurve_commonY <- calc_supplycurve(data,fc,myform=userfun)
supplycurve_indiviY <- calc_supplycurve(data,fc,myform=userfun,ylimit="individual")
remulator:::plot_curve(filtered[,,"raw",invert=TRUE],supplycurve_commonY,supplycurve_indiviY,infes=NA,emu_path="emulator",fitname="linear-no-flat",create_pdf=FALSE)
write.magpie(fc,file_name = paste0("emulator/SSP2-Ref/linear-no-flat/f30_bioen_price_replaced_flats.cs4r"))

setwd("~/Documents/0_GIT/magpie4-model/output/")

load("emulator/SSP2-26/linear/data_postfit_SSP2-26.Rdata")

zero <- fitcoef[,,"b"]<0.01

#* replace fitcoefficients for years that have flat fits (b==0)
fc <- fill_missing_years(fitcoef,zero)

supplycurve_commonY <- calc_supplycurve(data,fc,myform=userfun)
supplycurve_indiviY <- calc_supplycurve(data,fc,myform=userfun,ylimit="individual")

remulator:::plot_curve(filtered[,,"raw",invert=TRUE],supplycurve_commonY,supplycurve_indiviY,infes=NA,emu_path="emulator",fitname="linear-no-flat",create_pdf=FALSE)

library(magclass)
write.magpie(fc,file_name = paste0("emulator/SSP2-26/linear-no-flat/f30_bioen_price_replaced_flats.cs4r"))

```

# 2. MOINPUT
* copy the files produced by the emulator script (see 1.2) or by the replace-script (see 1.3) into "sources/MAgPIE" of your input data preparation folder
* run `calcOutput("BiomassPrices", round=6, file="f30_bioen_price.cs4r", realization="magpie_40")`
* this produces the file "output/default/f30_bioen_price.cs4r"*

# 3. REMIND
* checkout REMIND 2.0
* svn co http://subversion.pik-potsdam.de/svn/spark_remind/trunk
* place the output files from above in "modules/30_biomass/magpie_40/input/f30_bioen_price.cs4r"

# 4. Start coupled runs
* in your REMIND folder open "start_bundle_coupled.R" and adapt the settings in the first section
* adapt the "config/scenario_config.csv" and the "config/scenario_config_coupled.csv"
* before starting the runs check whether everything works `Rscipt start_bundle_coupled.R test`
* if the script cannot find a file you specified it shows this in red color
* if everything is fine start the coupled runs `Rscipt start_bundle_coupled.R`
